version: '3.3'

networks:
  net:
    driver: bridge

services:
  api:
      build:
        context: ./API
        dockerfile: Dockerfile
      networks:
        - net 
      ports:
        - "3000:3000"
      volumes:
        - ./API/index.js:/app/index.js

  cassandra-node1:
    image: bitnami/cassandra:4.0.4
    volumes:
      - './Cassandra:/docker-entrypoint-initdb.d'
    networks:
      - net  
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSADRA_PASSWORD=cassandra123

  cassandra-node2:
    image: bitnami/cassandra:4.0.4
    networks:
      - net
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSADRA_PASSWORD=cassandra123

  cassandra-node3:
    image: bitnami/cassandra:4.0.4
    networks:
      - net
    environment:
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-node1,cassandra-node2,cassandra-node3
      - CASSADRA_PASSWORD=cassandra123